config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :devices
  get 'about/index'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.order("RANDOM()").limit(30)
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :link, :price, :score, :watts, :picture, :keyword)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.order("RANDOM()").limit(100)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:picture, :price, :score, :link, :material)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/devices/_form.html.erb
<%= form_for(device) do |f| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>

  <div class="field">
    <%= f.label :watts %>
    <%= f.text_field :watts %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>

  <div class="field">
    <%= f.label :keyword %>
    <%= f.text_field :keyword %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,900" rel="stylesheet">
<style>
.navbar-collapse {
    max-height: 54px !important;
    background: #fff;
}
</style>
<body>

<div class="container">

<br><br>
<div class="left">
    <p class="section-head">Category</p>
    <label class="control control--checkbox">Men
        <input id="check-men" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">Women
        <input id="check-women" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">Kids
        <input id="check-kids" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>

    <p class="section-head section-price">Price</p>
    <center>
        <span class="price-input">$<input id="check-price-min" class="price-min" type="number" placeholder="Min"></span>
        <span class="price-input">$<input id="check-price-min" class="price-max" type="number" placeholder="Max"></span>
    </center>
<br>
    <p class="section-head">Brand</p>
    <label class="control control--checkbox">
        Acer
        <input id="check-acer" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">
        Apple
        <input id="check-apple" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">
        Asus
        <input id="check-asus" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">
        HP
        <input id="check-hp" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">
        Microsoft
        <input id="check-msi" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">
        Samsung
        <input id="check-samsung" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">
        Sony
        <input id="check-sony" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
</div>

<article>
    <% @devices.each do |device| %>

    <div class="square">
        <div class="content">
            <%= image_tag(device.picture, class: "img-responsive") %>
            <h2>device.brand</h2>
            <p>device.name</p>
            <p id="price">$<%= device.price %></p>
        </div>
    </div>
    <!--
        <% content_tag(:div, class: [ "card-" + product.section, "card-" + product.brand ]) %>
        <div class="square">
            <div class="content">
                <%= image_tag(product.picture, class: "img-responsive") %>
                <h2><%= product.brand %></h2>
                <p><%= product.name %></p>
                <p id="price">$<%= product.price %></p>

                <% if product.score < 10.0 %>
                    <p class="good-score">product.score</p>
                <% elsif product.score < 100.0 %>
                    <p class="ok-score">product.score</p>
                <% else %>
                    <p class="bad-score">product.score</p>
                <% end %>
            </div>
        </div>-->
    <% end %>
</article>

</div>

<script>
$('#check-acer').change(function() {
    if ($('#check-acer').is(':checked')) {
        $('.card-acer').show();
    } else {
        $('.card-acer').hide();
    }
});
$('#check-apple').change(function() {
    if ($('#check-apple').is(':checked')) {
        $('.card-apple').show();
    } else {
        $('.card-apple').hide();
    }
});
$('#check-asus').change(function() {
    if ($('#check-asus').is(':checked')) {
        $('.card-asus').show();
    } else {
        $('.card-asus').hide();
    }
});
$('#check-hp').change(function() {
    if ($('#check-hp').is(':checked')) {
        $('.card-hp').show();
    } else {
        $('.card-hp').hide();
    }
});
$('#check-msi').change(function() {
    if ($('#check-msi').is(':checked')) {
        $('.card-msi').show();
    } else {
        $('.card-msi').hide();
    }
});
$('#check-samsung').change(function() {
    if ($('#check-samsung').is(':checked')) {
        $('.card-samsung').show();
    } else {
        $('.card-samsung').hide();
    }
});
$('#check-sony').change(function() {
    if ($('#check-sony').is(':checked')) {
        $('.card-sony').show();
    } else {
        $('.card-sony').hide();
    }
});
$('#check-toshiba').change(function() {
    if ($('#check-toshiba').is(':checked')) {
        $('.card-toshiba').show();
    } else {
        $('.card-toshiba').hide();
    }
});
</script>

</body>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<div class="content">
<p id="notice"><%= notice %></p>

<p>
  <strong><%=@device.name %></strong> <br>
  <%= image_tag("https://" + @device.picture) %>
</p>

<p>
  <% unless @device.price %>
  This <%= @device.name.downcase %> has a price of <%= @device.price %>. Furthermore, it
  <% else %>
  Unfortunately, this website does not display the price, however, this <%= @device.name.downcase %>
  <% end %> has a score of <%= @device.score %>, and a power rating of <%= @device.watts %>, making it
  a
    <% if @device.score > 75 %>
        good deal
    <% elsif @device.score > 50 %>
        relatively good deal
    <% elsif @device.score > 25 %>
        relatively bad deal
    <% else %>
        bad deal
    <% end %>
</p>


  <%= link_to "Buy", @device.link, class: "btn btn-default" %>

<%= link_to 'Back', devices_path %>
</div>

app/views/layouts/_navbar.html.erb
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,900" rel="stylesheet">

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <% if current_page?(root_path) %>
                    <%= link_to "About", root_path(:anchor => "about") %>
                    <% else %>
                    <%= link_to "About", welcome_index_path(:anchor => "about") %>
                    <% end %>
                </li>
                <li>
                    <%= link_to "Clothes", products_path %>
                </li>
                <li>
                    <%= link_to "Electronics", devices_path %>
                </li>
            </ul>
            <div class="navbar-header">
                <h2><%= link_to "Fashion Tree", root_path, class: "navbar-brand" %></h2>

            </div>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <% unless current_user %>
                    <%= link_to "Register", new_user_registration_path %>
                </li>
                <li>
                    <%= link_to "Sign In", new_user_session_path %>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FashionTree</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :material %>
    <%= f.text_field :material %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,900" rel="stylesheet">
<style>
.navbar-collapse {
    max-height: 54px !important;
    background: #fff;
}
</style>

<body id="body">
    <br><br><br><br>
    <span class="search"><i class="fa fa-search" aria-hidden="true"></i>
    <input type="text" id="search-me" onkeydown="search(this)" placeholder="Search Shirts, Jeans, Dresses and more"></span>
    <br>



<div class="container">



<div class="left">
    <p class="section-head">Category</p>
    <label class="control control--checkbox">Men
        <input id="check-men" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">Women
        <input id="check-women" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">Kids
        <input id="check-kids" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>

    <p class="section-head section-price">Price</p>
    <center>
        <span class="price-input">$<input id="check-price-min" class="price-min" type="number" placeholder="Min"></span>
        <span class="price-input">$<input id="check-price-min" class="price-max" type="number" placeholder="Max"></span>
    </center>
<br>
    <p class="section-head">Brand</p>
    <label class="control control--checkbox">H&M
        <input id="check-hm" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">Nordstorm
        <input id="check-nordstorm" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <label class="control control--checkbox">Uniqlo
        <input id="check-uniqlo" type="checkbox"/>
        <div class="control__indicator"></div>
    </label>
    <p class="section-head">Sort By</p>


</div>
<script>
$('#check-men').change(function() {
    if ($('#check-men').is(':checked')) {
        $('.card-men').show();
        if (!($('#check-women').is(':checked'))) {
            $('.card-women').hide();
        }
        if (!($('#check-kids').is(':checked'))) {
            $('.card-kids').hide();
        }
    } else {
        $('.card-men').hide();
        if ( !($('#check-women').is(':checked')) && !($('#check-kids').is(':checked'))) {
            $('.card-women').show();
            $('.card-men').show();
            $('.card-kids').show();
        }
    }
});
$('#check-women').change(function() {
    if ($('#check-women').is(':checked')) {
        $('.card-women').show();
        if (!($('#check-kids').is(':checked'))) {
            $('.card-kids').hide();
        }
        if (!($('#check-men').is(':checked'))) {
            $('.card-men').hide();
        }
    } else {
        $('.card-women').hide();
        if ( !($('#check-kids').is(':checked')) && !($('#check-men').is(':checked'))) {
            $('.card-women').show();
            $('.card-men').show();
            $('.card-kids').show();
        }
    }
});
$('#check-kids').change(function() {
    if ($('#check-kids').is(':checked')) {
        $('.card-kids').show();
        if (!($('#check-women').is(':checked'))) {
            $('.card-women').hide();
        }
        if (!($('#check-men').is(':checked'))) {
            $('.card-men').hide();
        }
    } else {
        $('.card-kids').hide();
        if ( !($('#check-women').is(':checked')) && !($('#check-men').is(':checked'))) {
            $('.card-women').show();
            $('.card-men').show();
            $('.card-kids').show();
        }
    }
});
$('#check-hm').change(function() {
    if ($('#check-hm').is(':checked')) {
        $('.card-hm').show();
        if (!($('#check-uniqlo').is(':checked'))) {
            $('.card-uniqlo').hide();
        }
        if (!($('#check-nordstorm').is(':checked'))) {
            $('.card-nordstorm').hide();
        }
    } else {
        $('.card-hm').hide();
        if ( !($('#check-uniqlo').is(':checked')) && !($('#check-nordstorm').is(':checked'))) {
            $('.card-nordstorm').show();
            $('.card-hm').show();
            $('.card-uniqlo').show();
        }
    }
});
$('#check-nordstorm').change(function() {
    if ($('#check-nordstorm').is(':checked')) {
        $('.card-nordstorm').show();
        if (!($('#check-hm').is(':checked'))) {
            $('.card-hm').hide();
        }
        if (!($('#check-uniqlo').is(':checked'))) {
            $('.card-uniqlo').hide();
        }
    } else {
        $('.card-nordstorm').hide();
        if ( !($('#check-hm').is(':checked')) && !($('#check-uniqlo').is(':checked'))) {
            $('.card-nordstorm').show();
            $('.card-hm').show();
            $('.card-uniqlo').show();
        }
    }
});
$('#check-uniqlo').change(function() {
    if ($('#check-uniqlo').is(':checked')) {
        $('.card-uniqlo').show();
        if (!($('#check-hm').is(':checked'))) {
            $('.card-hm').hide();
        }
        if (!($('#check-nordstorm').is(':checked'))) {
            $('.card-nordstorm').hide();
        }
    } else {
        $('.card-uniqlo').hide();
        if ( !($('#check-hm').is(':checked')) && !($('#check-nordstorm').is(':checked'))) {
            $('.card-nordstorm').show();
            $('.card-hm').show();
            $('.card-uniqlo').show();
        }
    }
});
</script>

<article>
    <!--TODO: MODAL-->
    <% product_number = 0 %>
    <% @products.take(50).each do |product| %>
        <div data-kw="<%= product.keyword %>" class="square <%= 'card-' + product.section.downcase %> <%= 'card-' + product.brand.downcase %>">
            <div class="content">
                <%= link_to product.link do %>
                    <%= image_tag(product.picture, class: "img-responsive") %>
                    <span><b>Shop now</b></span>
                <% end %>
                <p class="product-brand">
                    <% if product.brand == "hm" %>
                        h&m
                    <% else %>
                        <%= product.brand %>
                    <% end %>
                </p>
                <p><%= product.name %></p>
                <p id="price">$<%= product.price %></p>
                <% if product.score == 0 %>
                    <p class="bad-score">98</p>
                <% elsif product.score < 20.0 %>
                    <p class="good-score"><%= product.score %></p>
                <% elsif product.score < 70.0 %>
                    <p class="ok-score"><%= product.score  %></p>
                <% else %>
                    <p class="bad-score"><%= product.score %></p>
                <% end %>
            </div>
        </div>
        <script>
        function showDiv() {
           document.getElementById('modal<%=49-product_number%>').style.display = "block";
        }
        function hideDiv() {
            document.getElementById('modal<%=49-product_number%>').style.display = "none";
        }

        </script>
        <%= content_tag :div, id: "temp" + (49 - product_number).to_s, data: {temp: product.keyword} do %>
        <%end%>
        <% product_number += 1 %>
    <% end %>
</article>

</div>

</body>
<script>
function search(ele) {
    if(event.keyCode == 13) {

        for (var i = 0; i < 50; i++) {
            var id = "temp" + i.toString();
            if (document.getElementById(id).getAttribute('data-temp') == document.getElementById('search-me').value){
                document.getElementById(id).style.display == "none";
                console.log(3);

            }

        }
    }
}
</script>

app/views/products/new.html.erb
<div class="body">
  <h1>New Product</h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="content">
    <p id="notice"><%= notice %></p>

    <p>
        <strong><%= @product.name%></strong> <br>
        <%= image_tag("https://"  + @product.picture) %>
    </p>

    <p>
        This <%= @product.name.downcase %> has a price of <%= @product.price %> and a score of <%= @product.score %>, making it
        a
        <% if @product.score > 75 %>
            good deal
        <% elsif @product.score > 50 %>
            relatively good deal
        <% elsif @product.score > 25 %>
            relatively bad deal
        <% else %>
            bad deal
        <% end %>
    </p>


    <%= link_to "Buy", @product.link, class: "btn btn-default" %>

    <%= link_to 'Back', products_path %>
</div>

app/views/welcome/index.html.erb
  <div class="parallax-img">
    <div class="image-text">
      <h2 class="lead">Economical and Ecological Clothing</h2>
    </div>
  </div>


  <div class="container">
    <div class="text-box">
      <h2> About </h2>
      <div id="about" class="description">
        Fashion Tree is for the economically and environmentally concerned shopper. As students, we understand that it's not easy to be eco
        friendly on a budget. Not only do many affordable brands have questionable ecological practices, brands that are eco friendly are often twice the
        price! Finding important products like clothes and electronics that are both eco friendly and affordable is like finding a needle in a haystack.
        Spending the time to read page after page of products only to find the one eco friendly option just isn't practical. Fortunately, Fashion Tree
        can solve this problem!
      </div>
      </div>
    </div>
    <div class="parallax-img-2"> </div>
    <div class="container">
      <div class="text-box">
        <h2> How </h2>
        <div id="how" class="description">
          Fashion Tree scans various product websites for critical information about the product, such as material composition, sourcing,
          price and energy cost. From there, a custom algorithm determines the environmental impact of the product.
          Furthermore, it compiles the overall impact of a given brand and displays it.
        </div>
      </div>
    </div>
    <div class="parallax-img-3"></div>